# Game settings
game-time-minutes: 5
progressive-task-difficulty: false
continue-game-after-end: false
# Tasks
fall: true
cactus: true
fire: true
lightning: true
creeper-explosion: true
tnt-explosion: true
pillager: true
fireball: true
entity-cramming: true
iron-golem: true
void: true
skeleton: true
zombie: true
lava: true
pointed-dripstone: true
sweet-berries: true
anvil: true
suffocation: true
trident: true
llama-spit: true
drown: true
bee: true
baby-hoglin: true
spider: true
enderman: true
pufferfish: true
wolf: true
freeze: true
tnt-minecart: true
firework-rocket: true
zombified-piglin: true
wither: true
magma: true
dispenser: true